# Generated by Django 5.1.5 on 2025-01-28 15:06

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_alter_link_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Имя должно быть в формате: Иванов Иван Иванович', regex='^[А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+ [А-ЯЁ][а-яё]+$')], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_address', message='Адрес может содержать буквы, \nцифры, пробелы и символы: , . -', regex='^[а-яё-А-Я0-9., ]+$'), django.core.validators.MinLengthValidator(5)], verbose_name='Адрес клиента'),
        ),
    ]
